# Generated by Django 5.0.7 on 2024-07-23 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_status',
            new_name='account_active_status',
        ),
    ]
