# Generated by Django 5.0.7 on 2024-07-23 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0002_rename_account_status_account_account_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
