# Generated by Django 5.0.7 on 2024-07-29 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0006_remove_user_account_number_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='banking_app.account'),
        ),
    ]
