# Generated by Django 5.0.7 on 2024-07-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0007_user_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_number',
        ),
    ]
