# Generated by Django 5.0.7 on 2024-07-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0009_user_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_number',
        ),
    ]
