# Generated by Django 5.0.7 on 2024-07-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0017_remove_account_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_number',
            new_name='account',
        ),
    ]
