# Generated by Django 5.0.7 on 2024-07-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0024_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
